name: init
on:
  create:
    branches:
      - master
jobs:
  init:
    runs-on: ubuntu-latest
    name: "initCreation"
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "this is fun"
          cat ${GITHUB_EVENT}